# Generated by Django 5.0.6 on 2024-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='target_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
