# Generated by Django 5.0 on 2024-05-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
