# Generated by Django 5.0 on 2024-05-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title', 'completed', 'created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
