# Generated by Django 5.0 on 2024-04-18 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 3, 49, 24, 970077, tzinfo=datetime.timezone.utc)),
        ),
    ]
