# Generated by Django 5.0 on 2024-05-01 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 5, 50, 0, 741224, tzinfo=datetime.timezone.utc)),
        ),
    ]
