# Generated by Django 5.0.6 on 2024-06-04 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 7, 31, 35, 175929, tzinfo=datetime.timezone.utc)),
        ),
    ]
