# Generated by Django 5.0.6 on 2024-06-05 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 6, 40, 27, 908960, tzinfo=datetime.timezone.utc)),
        ),
    ]
