# Generated by Django 5.0.6 on 2024-06-11 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 9, 35, 31, 680216, tzinfo=datetime.timezone.utc)),
        ),
    ]
