# Generated by Django 5.0 on 2024-04-27 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 6, 23, 58, 354961, tzinfo=datetime.timezone.utc)),
        ),
    ]
