# Generated by Django 5.0 on 2023-12-27 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 4, 18, 31, 447381, tzinfo=datetime.timezone.utc)),
        ),
    ]
