# Generated by Django 5.0 on 2024-01-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_date_joined'),
    ]

    operations = [
    ]
