# Generated by Django 5.0 on 2024-01-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20240101_1512'),
    ]

    operations = [
    ]
