# Generated by Django 5.0 on 2024-04-13 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_customuser_username_customuser_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 12, 33, 18, 941345, tzinfo=datetime.timezone.utc)),
        ),
    ]
